### ISSUE TITLE
A segunda issue - padronizar o css. 

### ISSUE THREAD

**Issue by gabicantarini** [Jheimys/interactive-rating-component-main#2]
Peço que revise o teu código css e siga as orientações para uma boa padronização.

**Comment by Jheimys** [comment]
Obrigado @gabicantarini, sua orientação foi muito importante e vou colocar em prática!

**Comment by Jheimys** [comment]
Obrigado @gabicantarini, sua orientação foi muito importante e vou colocar em prática!
